# Generated by Django 2.0.5 on 2018-05-16 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hvk', '0002_auto_20180515_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oib', models.CharField(max_length=13, null=True, unique=True, verbose_name='OIB')),
                ('spol', models.CharField(choices=[('m', 'muško'), ('f', 'žensko')], max_length=1, null=True, verbose_name='Spol')),
                ('dat_rod', models.DateField(null=True, verbose_name='Datum rođenja')),
                ('slika', models.ImageField(max_length=255, null=True, upload_to='hvk_clanovi', verbose_name='Slika')),
                ('ime', models.CharField(max_length=35, null=True, verbose_name='Ime')),
                ('prezime', models.CharField(max_length=35, null=True, verbose_name='Prezime')),
                ('py_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Korisničko ime')),
            ],
            options={
                'verbose_name': 'Član',
                'ordering': ['prezime', 'ime', 'dat_rod'],
                'verbose_name_plural': 'Članovi',
            },
        ),
    ]
