# Generated by Django 2.0.5 on 2018-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvk', '0003_clan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='dat_rod',
            field=models.DateField(blank=True, null=True, verbose_name='Datum rođenja'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='ime',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='oib',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='OIB'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='prezime',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Prezime'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='slika',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='hvk_clanovi', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='spol',
            field=models.CharField(blank=True, choices=[('m', 'muško'), ('f', 'žensko')], max_length=1, null=True, verbose_name='Spol'),
        ),
    ]
