# Generated by Django 2.0.5 on 2018-05-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0005_auto_20180516_1424'),
        ('hvk', '0004_auto_20180516_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PravnaOsoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oib', models.CharField(max_length=13, unique=True, verbose_name='OIB')),
                ('naziv', models.CharField(max_length=80, verbose_name='Naziv')),
                ('ziro', models.CharField(max_length=21, verbose_name='Žiro-račun')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.VrstaPO', verbose_name='Vrsta')),
            ],
            options={
                'db_table': 'hvk_pravna_osoba',
                'verbose_name_plural': 'Pravne osobe',
                'verbose_name': 'Pravna osoba',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='RadnoMjesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_od', models.DateField(verbose_name='Od')),
                ('dat_do', models.DateField(blank=True, null=True, verbose_name='Do')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hvk.Clan', verbose_name='Radnik (član HVK)')),
                ('nkz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.Nkz', verbose_name='Zvanje po NKZ')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hvk.PravnaOsoba', verbose_name='Pravna osoba')),
            ],
            options={
                'db_table': 'hvk_radno_mjesto',
                'verbose_name_plural': 'Radna mjesta',
                'verbose_name': 'Radno mjesto',
                'ordering': ['-dat_od'],
            },
        ),
    ]
