# Generated by Django 2.0.5 on 2018-05-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0005_auto_20180516_1424'),
        ('hvk', '0005_pravnaosoba_radnomjesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Djelatnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_od', models.DateField(verbose_name='Od')),
                ('dat_do', models.DateField(blank=True, null=True, verbose_name='Do')),
                ('nkd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.Nkd', verbose_name='NKD')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hvk.PravnaOsoba', verbose_name='Pravna osoba')),
            ],
            options={
                'verbose_name_plural': 'Djelatnosti',
                'ordering': ['nkd'],
                'db_table': 'djelatnost',
                'verbose_name': 'Djelatnost',
            },
        ),
        migrations.CreateModel(
            name='KontaktPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.CharField(max_length=80, verbose_name='Kontakt')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hvk.PravnaOsoba', verbose_name='Pravna osoba')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.VrstaKontakta', verbose_name='Vrsta')),
            ],
            options={
                'verbose_name_plural': 'Kontakti',
                'ordering': ['vrsta'],
                'verbose_name': 'Kontakt',
                'db_table': 'hvk_po_kontakt',
            },
        ),
        migrations.CreateModel(
            name='MjesnostPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=80, verbose_name='Ulica i kućni broj')),
                ('mjesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.Mjesto', verbose_name='Mjesto')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hvk.PravnaOsoba', verbose_name='Pravna osoba')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.VrstaMjesnosti', verbose_name='Vrsta')),
            ],
            options={
                'verbose_name_plural': 'Mjesnosti',
                'ordering': ['mjesto'],
                'db_table': 'hvk_po_mjesnost',
                'verbose_name': 'Mjesnost',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mjesnostpo',
            unique_together={('mjesto', 'po', 'vrsta')},
        ),
        migrations.AlterUniqueTogether(
            name='djelatnost',
            unique_together={('po', 'nkd')},
        ),
    ]
