# Generated by Django 2.0.5 on 2018-05-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hvk', '0006_auto_20180517_0914'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kontaktpo',
            table='hvk_kontakt_po',
        ),
        migrations.AlterModelTable(
            name='mjesnostpo',
            table='hvk_mjesnost_po',
        ),
    ]
