# Generated by Django 2.0.5 on 2018-05-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hvk', '0008_auto_20180517_0916'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='djelatnost',
            table=None,
        ),
    ]
