# Generated by Django 2.0.5 on 2018-05-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0006_auto_20180517_1009'),
        ('hvk', '0009_auto_20180517_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktCl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.CharField(max_length=80, verbose_name='Kontakt')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hvk.Clan', verbose_name='Član')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.VrstaKontakta', verbose_name='Vrsta')),
            ],
            options={
                'ordering': ['vrsta'],
                'verbose_name_plural': 'Kontakti',
                'verbose_name': 'Kontakt',
                'db_table': 'hvk_kontakt_cl',
            },
        ),
        migrations.CreateModel(
            name='MjesnostCl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=80, verbose_name='Ulica i kućni broj')),
                ('mjesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.Mjesto', verbose_name='Mjesto')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hvk.Clan', verbose_name='Član')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.VrstaMjesnosti', verbose_name='Vrsta')),
            ],
            options={
                'ordering': ['mjesto'],
                'verbose_name': 'Mjesnost',
                'db_table': 'hvk_mjesnost_cl',
                'verbose_name_plural': 'Mjesnosti',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mjesnostcl',
            unique_together={('mjesto', 'po', 'vrsta')},
        ),
    ]
