# Generated by Django 2.0.5 on 2018-06-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0006_auto_20180517_1009'),
        ('hvk', '0011_clanstvo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mjesnostcl',
            old_name='po',
            new_name='clan',
        ),
        migrations.AlterUniqueTogether(
            name='mjesnostcl',
            unique_together={('mjesto', 'clan', 'vrsta')},
        ),
    ]
