# Generated by Django 2.0.5 on 2018-06-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0006_auto_20180517_1009'),
        ('hvk', '0013_auto_20180613_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kontaktcl',
            unique_together={('clan', 'vrsta', 'sadrzaj')},
        ),
        migrations.AlterUniqueTogether(
            name='kontaktpo',
            unique_together={('po', 'vrsta', 'sadrzaj')},
        ),
    ]
