# Generated by Django 2.0.5 on 2018-05-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mjesto',
            fields=[
                ('ozn', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('pbr', models.CharField(max_length=5, null=True, verbose_name='Poštanski broj')),
                ('naziv', models.CharField(max_length=80, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['naziv'],
                'verbose_name': 'Mjesto',
                'verbose_name_plural': 'Mjesta',
            },
        ),
        migrations.CreateModel(
            name='Nkd',
            fields=[
                ('ozn', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.TextField(max_length=255, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['ozn'],
                'verbose_name': 'Djelatnost po NKD',
                'verbose_name_plural': 'Djelatnosti po NKD',
            },
        ),
        migrations.CreateModel(
            name='Nkz',
            fields=[
                ('ozn', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.TextField(max_length=255, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['ozn'],
                'verbose_name': 'Zvanje po NKZ',
                'verbose_name_plural': 'Zvanja po NKZ',
            },
        ),
        migrations.CreateModel(
            name='ObrStupanj',
            fields=[
                ('ozn', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.TextField(max_length=80, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['naziv'],
                'verbose_name': 'Obrazovni stupanj',
                'verbose_name_plural': 'Obrazovni stupnjevi',
                'db_table': 'kat_obr_stupanj',
            },
        ),
        migrations.CreateModel(
            name='Opcina',
            fields=[
                ('ozn', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='DGU oznaka')),
                ('naziv', models.CharField(max_length=80, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['naziv'],
                'verbose_name': 'Općina',
                'verbose_name_plural': 'Općine',
            },
        ),
        migrations.CreateModel(
            name='VrstaKontakta',
            fields=[
                ('ozn', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.CharField(max_length=40, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['naziv'],
                'verbose_name': 'Vrsta kontakta',
                'verbose_name_plural': 'Vrste kontakta',
                'db_table': 'kat_vrsta_kontakta',
            },
        ),
        migrations.CreateModel(
            name='VrstaMjesnosti',
            fields=[
                ('ozn', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.CharField(max_length=40, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['naziv'],
                'verbose_name': 'Vrsta mjesnosti',
                'verbose_name_plural': 'Vrste mjesnosti',
                'db_table': 'kat_vrsta_mjesnosti',
            },
        ),
        migrations.CreateModel(
            name='VrstaPO',
            fields=[
                ('ozn', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.CharField(max_length=40, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['naziv'],
                'verbose_name': 'Vrsta pravne osobe',
                'verbose_name_plural': 'Vrste pravne osobe',
                'db_table': 'kat_vrsta_po',
            },
        ),
        migrations.CreateModel(
            name='Zupanija',
            fields=[
                ('ozn', models.IntegerField(primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.CharField(max_length=50, unique=True, verbose_name='Naziv')),
            ],
            options={
                'ordering': ['naziv'],
                'verbose_name': 'Županija',
                'verbose_name_plural': 'Županije',
            },
        ),
        migrations.AddField(
            model_name='opcina',
            name='zupanija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.Zupanija', verbose_name='Županija'),
        ),
        migrations.AddField(
            model_name='mjesto',
            name='opcina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.Opcina', verbose_name='Općina'),
        ),
    ]
