# Generated by Django 2.0.5 on 2018-05-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrstaClanstva',
            fields=[
                ('ozn', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Oznaka')),
                ('naziv', models.CharField(max_length=40, unique=True, verbose_name='Naziv')),
            ],
            options={
                'verbose_name_plural': 'Vrste članstva',
                'ordering': ['naziv'],
                'db_table': 'kat_vrsta_clanstva',
                'verbose_name': 'Vrsta članstva',
            },
        ),
    ]
