# Generated by Django 2.0.5 on 2018-05-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0003_auto_20180516_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrTitula',
            fields=[
                ('ozn', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Kratica')),
                ('naziv', models.TextField(max_length=255, unique=True, verbose_name='Puni naziv')),
                ('razina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kat.ObrRazina', verbose_name='Razina')),
            ],
            options={
                'ordering': ['ozn'],
                'verbose_name_plural': 'Obrazovne titule',
                'db_table': 'kat_obr_titula',
                'verbose_name': 'Obrazovna titula',
            },
        ),
    ]
