# Generated by Django 2.0.5 on 2018-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0004_obrtitula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrrazina',
            options={'ordering': ['ozn'], 'verbose_name': 'Obrazovna razina', 'verbose_name_plural': 'Obrazovne razine'},
        ),
        migrations.AlterField(
            model_name='obrrazina',
            name='naziv',
            field=models.TextField(max_length=255, unique=True, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='obrrazina',
            name='ozn',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Oznaka'),
        ),
    ]
