# Generated by Django 2.0.5 on 2018-05-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kat', '0005_auto_20180516_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcina',
            name='naziv',
            field=models.CharField(max_length=80, verbose_name='Naziv'),
        ),
    ]
