from .mjesto_admin import MjestoAdmin
from .nkd_admin import NkdAdmin
from .nkz_admin import NkzAdmin
from .obr_razina_admin import ObrRazinaAdmin
from .obr_titula_admin import ObrTitulaAdmin
from .opcina_admin import OpcinaAdmin
from .prestanak_cl_admin import PrestanakClAdmin
from .vrsta_clanstva_admin import VrstaClanstvaAdmin
from .vrsta_kontakta_admin import VrstaKontaktaAdmin
from .vrsta_mjesnosti_admin import VrstaMjesnostiAdmin
from .vrsta_po_admin import VrstaPoAdmin
from .zupanija_admin import ZupanijaAdmin
