# Generated by Django 2.0.5 on 2018-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MUPRegOsoba',
            fields=[
                ('oib', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=35)),
                ('prezime', models.CharField(max_length=35)),
                ('spol', models.CharField(max_length=1)),
                ('dat_rod', models.DateField()),
                ('preb_ulica_kbr', models.CharField(max_length=45)),
                ('preb_mjesto_sifra', models.CharField(max_length=6)),
                ('preb_mjesto_naziv', models.CharField(max_length=32)),
                ('bora_ulica_kbr', models.CharField(blank=True, max_length=45, null=True)),
                ('bora_mjesto_sifra', models.CharField(blank=True, max_length=6, null=True)),
                ('bora_mjesto_naziv', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'sim_mup_reg_osoba',
            },
        ),
    ]
